//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_CNPM_LT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.YEUTHICHes = new HashSet<YEUTHICH>();
            ANH = "~/Data/roomImg/DefaultRoom.jpg";
        }
    
        public string MA_PHONG { get; set; }
        public string ID_TK { get; set; }

        [Required(ErrorMessage = "Không được để trống Tên Phòng")]
        public string TENPhong { get; set; }
        public string TRANGTHAI { get; set; }
        [Required(ErrorMessage = "Không được để trống Giá")]
        public Nullable<double> GIA { get; set; }
        [Required(ErrorMessage = "Không được để Ảnh")]
        public string ANH { get; set; }
        [Required(ErrorMessage = "Không được để trống Mã loại")]
        public string MaLoai { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<byte> DaDuyet { get; set; }
        [Required(ErrorMessage = "Không được để trống Nội dung")]
        public string NoiDung { get; set; }
        [Required(ErrorMessage = "Không được để trống Địa chỉ")]
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUTHICH> YEUTHICHes { get; set; }
    }
}
