use MASTER

create database QLKS_CNPM
GO
use QLKS_CNPM
GO


CREATE TABLE LOAITAIKHOAN
(
	ID_LOAITK CHAR (10) PRIMARY KEY,
	TENLOAITK NVARCHAR (100)
);


create table TAIKHOAN
(
	ID_TK VARCHAR (10) PRIMARY KEY,
	TenTK NVARCHAR (255),
	Gmail NVARCHAR (255),
	ANH VARCHAR(255),
	PASS VARCHAR(100),
	SDT VARCHAR (10),
	LOAITK CHAR (10) REFERENCES LOAITAIKHOAN (ID_LOAITK)
);

CREATE TABLE LOAIPHONG
(
	MaLoai varchar(10) primary key,
	TenLoai nvarchar(30), 
	GhiChu nvarchar(250),
	DuongDanAnh varchar(50)
);


GO
CREATE  TABLE PHONG
(
	MA_PHONG VARCHAR(10) PRIMARY KEY,
	ID_TK VARCHAR(10) references TAIKHOAN(ID_TK),
	TENPhong NVARCHAR(100),
	TRANGTHAI NVARCHAR(100),
	GIA float,
	NoiDung NVARCHAR,
	ANH NVARCHAR(255),
	MaLoai varchar(10) references LoaiPhong(MaLoai),
	DADUYET BIT,
	DanhGia float,
	BinhLuan NVARCHAR,
	DiaChi NVARCHAR
);

GO
CREATE TABLE YEUTHICH(
	ID int PRIMARY KEY,
	ID_TK VARCHAR(10) references TAIKHOAN(ID_TK),
	MA_PHONG VARCHAR(10) references PHONG(MA_PHONG)
)


GO
CREATE  TABLE GIAMGIA
(
	MAGIAM CHAR(10) PRIMARY KEY,
	TENMAGIAM NVARCHAR(50),
	SOTIEN FLOAT,
	GHICHU NVARCHAR (255)
);
GO
CREATE  TABLE HOADON
(
	MAHD CHAR(10) PRIMARY KEY,
	MAKH VARCHAR(10) REFERENCES TAIKHOAN(ID_TK),
	MA_PHONG VARCHAR(10) REFERENCES PHONG(MA_PHONG),
	MAGIAM CHAR(10) REFERENCES GIAMGIA(MAGIAM),
	TONGTIEN FLOAT,
	NgayDat date,
	NgayDen date,
	NgayTra date,
	TrangThai NVARCHAR 
);


GO
CREATE TABLE BCDT
(
	MABC CHAR(10) PRIMARY KEY,
	MAHD CHAR(10) REFERENCES HOADON(MAHD),
	NGAY DATE,
	TONGTHU INT,
);

GO
CREATE TABLE HOANTIEN
(
	MAHD CHAR(10) REFERENCES HOADON(MAHD),
	ID_TK VARCHAR(10) REFERENCES TAIKHOAN(ID_TK),
	NGAYHOAN DATE PRIMARY KEY,
	SOTIENHOAN INT
);
GO